title       = "nihreporter"
baseURL     = "https://nihreporter-cli.tamnd.com/"
description = "A command line for nihreporter."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/nihreporter-cli"
